---
- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: Install system packages
  ansible.builtin.apt:
    name:
      - gpg-agent
      - git
      - supervisor
      - nginx
      - logrotate
  ignore_errors: true
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: NodeJS deb source
  block:
    - name: Download nodesource gpg key
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /etc/apt/trusted.gpg.d/nodesource.asc
        checksum: sha256:b42e0321dabdc24e892115da705cf061167eac12a317f23d329862d0aa0a271d
        mode: "0644"
      ignore_errors: true
      retries: 5
      delay: 10
      register: result
      until: result is success

    - name: Remove nodejs 20.x ppa for apt repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/nodesource.asc] https://deb.nodesource.com/node_20.x nodistro main"
        state: absent

    - name: Add nodejs 24.x ppa for apt repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/nodesource.asc] https://deb.nodesource.com/node_24.x nodistro main"

- name: Yarn deb source
  block:
    - name: Download dl.yarnpkg.com gpg key
      ansible.builtin.get_url:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        dest: /etc/apt/trusted.gpg.d/yarnpkg.asc
        checksum: sha256:f8f78154312934e7894e29da119c9fb06b489d36e0b36ec1538a5b8486a2f59e
        mode: "0644"
      ignore_errors: true
      retries: 5
      delay: 10
      register: result
      until: result is success

    - name: Add nodejs 20.x ppa for apt repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/yarnpkg.asc] https://dl.yarnpkg.com/debian/ stable main"

- name: Install nodejs and yarn
  ansible.builtin.apt:
    cache_valid_time: 3000
    name:
      - nodejs
      - yarn
    state: latest
  ignore_errors: true
  retries: 5
  delay: 10
  register: result
  until: result is success
