---
- name: Apt tasks
  ansible.builtin.import_tasks: apt.yml
  tags: [wifi-login-pages, apt]

- name: Yarn tasks
  ansible.builtin.import_tasks: yarn.yml
  tags: [wifi-login-pages, yarn]

- name: Supervisor tasks
  ansible.builtin.import_tasks: supervisor.yml
  tags: [wifi-login-pages, supervisor]

- name: Nginx tasks
  ansible.builtin.import_tasks: nginx.yml
  tags: [wifi-login-pages, nginx]
