---
- name: Converge
  hosts: all
  become: true

  vars:
    wifi_login_pages_domains: ["localhost"]

  tasks:
    - name: "Include ansible role"
      include_role:
        name: "openwisp.wifi_login_pages"
