---

- name: Verify
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Checking file is uploaded
      stat:
        path: "/opt/openwisp2/wifi-login-pages/organizations/default/testfile"
      register: config_file

    - name: File exists
      debug:
        msg: "The file is uploaded"
      when: config_file.stat.exists

    - name: File do not exists
      fail:
        msg: "The file is not uploaded."
      when: not config_file.stat.exists

    - name: Checking translation is copied
      stat:
        path: "/opt/openwisp2/wifi-login-pages/i18n/en.custom.po"
      register: translation_file

    - name: Translation file exists
      debug:
        msg: "The file is uploaded"
      when: translation_file.stat.exists

    - name: Translation file do not exists
      fail:
        msg: "The file is not uploaded."
      when: not translation_file.stat.exists

    - name: Checking static file is copied
      stat:
        path: "/opt/openwisp2/wifi-login-pages/static/test_static_file"
      register: static_file

    - name: Static file exists
      debug:
        msg: "The file is uploaded"
      when: static_file.stat.exists

    - name: Static file do not exists
      fail:
        msg: "The file is not uploaded."
      when: not static_file.stat.exists
