---
- name: Start and enable supervisor service
  service:
    name: supervisor
    state: started
    enabled: yes

- name: Update supervisor configuration
  command: supervisorctl update wifi_login_pages
  register: supervisord_update_wifi_login_pages

- name: Restart wifi_login_pages
  command: supervisorctl restart wifi_login_pages
  when: not (supervisord_update_wifi_login_pages is defined and "wifi_login_pages:" in supervisord_update_wifi_login_pages.stdout)

- name: restart nginx
  service:
    name: nginx
    state: restarted
