---
- name: Reload supervisor
  ansible.builtin.service:
    name: supervisor
    state: restarted
  become: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
