---
- name: Start and enable supervisor service
  service:
    name: supervisor
    state: started
    enabled: yes

- name: reload supervisor
  shell: |
    supervisorctl reread
    supervisorctl update
    supervisorctl restart wifi_login_pages || supervisorctl start wifi_login_pages

- name: restart nginx
  service:
    name: nginx
    state: restarted
