---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
  lint: |
    set -e
    yamllint .
    ansible-lint
platforms:
  - name: "${ROLE_NAME:-instance}-${MOLECULE_DISTRO}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO}-ansible:${tag:-latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    MOLECULE_NO_LOG: false
  playbooks:
    converge: ../resources/${MOLECULE_PLAYBOOK:-converge.yml}
    verify: ../resources/verify.yml
  config_options:
    defaults:
      stdout_callback: community.general.yaml
      bin_ansible_callbacks: true
verifier:
  name: ansible
