---
name: Ansible OpenWISP WiFi Login Pages CI Build

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.distro }}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2404
          - ubuntu2204
          - ubuntu2004
          - debian12
          - debian11

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        id: deps
        run: |
          pip install -U pip wheel setuptools
          pip install -r requirements-test.txt
          ansible-galaxy collection install "community.general:>=3.6.0"

      - name: QA checks
        run: |
          openwisp-qa-check --skip-isort --skip-flake8 --skip-checkmigrations --skip-black

      - name: Tests
        if: ${{ !cancelled() && steps.deps.conclusion == 'success' }}
        run: |
          mkdir -p ~/.ansible/roles
          ln -s $GITHUB_WORKSPACE ~/.ansible/roles/openwisp.wifi_login_pages
          molecule test
        env:
          ROLE_NAME: openwisp2
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
